type DogsForAdoptionType = {
  id: number,
  name: string;
  gender: string,
  age: number,
  weight: number,
  imageUrl: string,
  breed: string,
  behavior: string,
  empathy: string,

}


export const dogsForAdoption: DogsForAdoptionType[] = [
    {
      id: 1,
      name: "Max",
      gender: "Male",
      age: 2,
      weight: 20,
      imageUrl: "golden retriever - portrait",
      breed: "Labrador Retriever",
      behavior: "He is friendly and energetic, loves to play fetch.",
      empathy: "Max is great with other animals and children, he loves to make new friends and is always up for some fun. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 2,
      name: "Luna",
      gender: "Female",
      age: 3,
      weight: 15,
      imageUrl: "beage-portrait",
      breed: "Beagle",
      behavior: "She is curious and playful, loves to explore.",
      empathy: "Luna is very gentle and patient with other animals and children, she has a kind and loving nature that makes her a joy to be around. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 3,
      name: "Charlie",
      gender: "Male",
      age: 1,
      weight: 10,
      imageUrl: "chihuaha portrait",
      breed: "Chihuahua",
      behavior: "He is lively and affectionate, loves attention.",
      empathy: "Charlie is a social butterfly who loves meeting new people and animals, he's always up for a cuddle and will never say no to a good belly rub. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 4,
      name: "Bella",
      gender: "Female",
      age: 4,
      weight: 25,
      imageUrl: "golden retriever - portrait",
      breed: "Golden Retriever",
      behavior: "She is gentle and obedient, loves to please.",
      empathy: "Bella is very caring and protective of other animals and children, she has a calm and patient personality that makes her a great companion for all ages. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 5,
      name: "Rocky",
      gender: "Male",
      age: 5,
      weight: 30,
      imageUrl: "german shepherd portrait",
      breed: "German Shepherd",
      behavior: "He is intelligent and loyal, loves to learn.",
      empathy: "Rocky has a strong sense of loyalty and empathy, he will always put others first and is very protective of his friends and family. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 6,
      name: "Daisy",
      gender: "Female",
      age: 2,
      weight: 18,
      imageUrl: "bulldog portrait",
      breed: "Bulldog",
      behavior: "She is stubborn and affectionate, loves to snuggle.",
      empathy: "Daisy has a heart of gold and loves to be around other animals and children, she's very loyal and protective of those she cares about. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 7,
      name: "Cooper",
      gender: "Male",
      age: 3,
      weight: 22,
      imageUrl: "siberian husky portrait",
      breed: "Siberian Husky",
      behavior: "He is energetic and playful, loves to run.",
      empathy: "Cooper is very social and loves to play with other animals and children, he has a gentle and loving personality that makes him a great addition to any family. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
        id: 8,
        name: "Taio",
        gender: "male",
        age: 4,
        weight: 50,
        imageUrl: "boxer-potrait",
        breed: "Boxer",
        behavior: "He is energetic and friendly.",
        empathy: "Taio loves to play and is always eager to meet new dogs. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. "
      },
      {
        id: 9,
        name: "Lara",
        gender: "female",
        age: 2,
        weight: 20,
        imageUrl: "shih tzu portrait",
        breed: "Shih Tzu",
        behavior: "She is affectionate and playful.",
        empathy: "Lara is very gentle and loves to play with dogs of all sizes. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
      {
        id: 10,
        name: "Rela",
        gender: "female",
        age: 3,
        weight: 25,
        imageUrl: "australian shepherd-portrait2",
        breed: "Australian Shepherd",
        behavior: "She is smart and loyal.",
        empathy: "Rela is cautious around other dogs but warms up quickly. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
      {
        id: 11,
        name: "Aida",
        gender: "female",
        age: 5,
        weight: 25,
        imageUrl: "australianportrait",
        breed: "Australian Shepherd",
        behavior: "She is smart and loyal.",
        empathy: "Rela is cautious around other dogs but warms up quickly. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
  
];
