export const dogsForAdoption = [
    {
      id: 1,
      name: "Max",
      gender: "Male",
      age: 2,
      weight: 20,
      imageUrl: "https://dogpics.com/max.jpg",
      breed: "Labrador Retriever",
      behavior: "Friendly and energetic, loves to play fetch",
      empathy: "Max is great with other animals and children, he loves to make new friends and is always up for some fun.",
    },
    {
      id: 2,
      name: "Luna",
      gender: "Female",
      age: 3,
      weight: 15,
      imageUrl: "https://dogpics.com/luna.jpg",
      breed: "Beagle",
      behavior: "Curious and playful, loves to explore",
      empathy: "Luna is very gentle and patient with other animals and children, she has a kind and loving nature that makes her a joy to be around.",
    },
    {
      id: 3,
      name: "Charlie",
      gender: "Male",
      age: 1,
      weight: 10,
      imageUrl: "https://dogpics.com/charlie.jpg",
      breed: "Chihuahua",
      behavior: "Lively and affectionate, loves attention",
      empathy: "Charlie is a social butterfly who loves meeting new people and animals, he's always up for a cuddle and will never say no to a good belly rub.",
    },
    {
      id: 4,
      name: "Bella",
      gender: "Female",
      age: 4,
      weight: 25,
      imageUrl: "https://dogpics.com/bella.jpg",
      breed: "Golden Retriever",
      behavior: "Gentle and obedient, loves to please",
      empathy: "Bella is very caring and protective of other animals and children, she has a calm and patient personality that makes her a great companion for all ages.",
    },
    {
      id: 5,
      name: "Rocky",
      gender: "Male",
      age: 5,
      weight: 30,
      imageUrl: "https://dogpics.com/rocky.jpg",
      breed: "German Shepherd",
      behavior: "Intelligent and loyal, loves to learn",
      empathy: "Rocky has a strong sense of loyalty and empathy, he will always put others first and is very protective of his friends and family.",
    },
    {
      id: 6,
      name: "Daisy",
      gender: "Female",
      age: 2,
      weight: 18,
      imageUrl: "https://dogpics.com/daisy.jpg",
      breed: "Bulldog",
      behavior: "Stubborn and affectionate, loves to snuggle",
      empathy: "Daisy has a heart of gold and loves to be around other animals and children, she's very loyal and protective of those she cares about.",
    },
    {
      id: 7,
      name: "Cooper",
      gender: "Male",
      age: 3,
      weight: 22,
      imageUrl: "https://dogpics.com/cooper.jpg",
      breed: "Siberian Husky",
      behavior: "Energetic and playful, loves to run",
      empathy: "Cooper is very social and loves to play with other animals and children, he has a gentle and loving personality that makes him a great addition to any family.",
    },
    {
        id: 8,
        name: "Taio",
        gender: "male",
        age: 4,
        weight: "50 lbs",
        imageUrl: "https://dogpics.com/Taio.jpg",
        breed: "Boxer",
        behavior: "energetic and friendly",
        empathyWithAnimals: "Taio loves to play and is always eager to meet new dogs",
        empathyWithChildren: "Taio is very gentle with children and loves to play with them",
      },
      {
        id: 9,
        name: "Lara",
        gender: "female",
        age: 2,
        weight: "20 lbs",
        imageUrl: "https://dogpics.com/Lara.jpg",
        breed: "Shih Tzu",
        behavior: "affectionate and playful",
        empathyWithAnimals: "Lara is very gentle and loves to play with dogs of all sizes",
        empathyWithChildren: "Lara is patient and loves to be around children",
      },
      {
        id: 10,
        name: "Rela",
        gender: "female",
        age: 3,
        weight: "25 lbs",
        imageUrl: "https://dogpics.com/Rela.jpg",
        breed: "Australian Shepherd",
        behavior: "smart and loyal",
        empathyWithAnimals: "Rela is cautious around other dogs but warms up quickly",
        empathyWithChildren: "Rela is gentle with children and loves to be around them",
      },
  
];
